### PR TITLE
Modified reg-ex patterns to match Aurora's read-only endpoints

### PR DESCRIPTION
**Pull request by timr**
This PR allows the driver to discover and connect to other servers within an Aurora cluster when a read-only cluster endpoint is used. A read-only cluster endpoint used in the JDBC url for multi-region / single master deployments where a region may only have read replicas. Read-only cluster endpoints contain "cluster-ro-" in there names instead of "cluster-" for master clusters.

RO: my-aurora-cluster-1.cluster-ro-muca838tbv0q.us-west-2.rds.amazonaws.com
RW: my-aurora-cluster-1.cluster-muca838tbv0q.us-west-2.rds.amazonaws.com

### CODE REVIEW

**Comment by rusher** [comment]
Hi, this would need lots more change. 
Actual aurora implementation creates 2 underlying connections: one to the writer, one to a reader. 
Regex would permit to connect a reader, but the driver will check read/write server state and try indefinitely to connect the master.

Connecting only to read server can be done using standard connection string 'jdbc:mariadb://<some.cluster-ro.region.rds.amazonaws.com>/db' or 'jdbc:mariadb:loadbalance://reader1,reader2,...readerX/db'

The first one has the advantage of using new readers added immediately.

**Comment by timr** [comment]
> Hi, this would need lots more change.
> Actual aurora implementation creates 2 underlying connections: one to the writer, one to a reader.
> Regex would permit to connect a reader, but the driver will check read/write server state and try indefinitely to connect the master.
> 
> Connecting only to read server can be done using standard connection string 'jdbc:mariadb://<some.cluster-ro.region.rds.amazonaws.com>/db' or 'jdbc:mariadb:loadbalance://reader1,reader2,...readerX/db'
> 
> The first one has the advantage of using new readers added immediately.

Hi @rusher,

The first example you highlighted near the end is the condition I'm trying to fix. I've added unit tests to help demonstrate the issue.

- Tim

**Comment by timr** [comment]
Going to revisit this a different way.

**Comment by plebedev** [comment]
Does it support `aurora` mode in the connection string, like
`jdbc:mariadb:aurora://<some.cluster-ro.region.rds.amazonaws.com>/db` ?

We've tried it and got
```
Caused by: java.sql.SQLException: Communications link failure with primary. No active connection found for master.
at org.mariadb.jdbc.internal.failover.AbstractMastersListener.throwFailoverMessage(AbstractMastersListener.java:563) ~[mariadb-java-client-2.6.0.jar:?]
at org.mariadb.jdbc.internal.failover.impl.MastersSlavesListener.checkInitialConnection(MastersSlavesListener.java:350) ~[mariadb-java-client-2.6.0.jar:?]
at org.mariadb.jdbc.internal.failover.impl.MastersSlavesListener.initializeConnection(MastersSlavesListener.java:179) ~[mariadb-java-client-2.6.0.jar:?]
at org.mariadb.jdbc.internal.failover.FailoverProxy.<init>(FailoverProxy.java:120) ~[mariadb-java-client-2.6.0.jar:?]
at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:607) ~[mariadb-java-client-2.6.0.jar:?]
at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:150) ~[mariadb-java-client-2.6.0.jar:?]
at org.mariadb.jdbc.MariaDbDataSource.getConnection(MariaDbDataSource.java:275) ~[mariadb-java-client-2.6.0.jar:?]
at org.mariadb.jdbc.MariaDbDataSource.getXAConnection(MariaDbDataSource.java:453) ~[mariadb-java-client-2.6.0.jar:?]
at com.atomikos.jdbc.AtomikosXAConnectionFactory.createPooledConnection(AtomikosXAConnectionFactory.java:43) ~[transactions-jdbc-4.0.6.jar:?]
... 24 more


```

**Pull request closed without merging**
